---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-db
  description: Backstage Database
  annotations:
    github.com/project-slug: ServerlessOpsIO/backstage-app
    io.serverlessops/rds-engine: aurora-postgresql
spec:
  type: database
  lifecycle: production
  owner: group:00gjdgxs1ur6lsu
  system: backstage
  domain: infrastructure